# 이 파일은 .github/workflows/automation.yml 경로에 저장됩니다.
name: Daily Snippet Automation

on:
  schedule:
    # 매일 오전 8시 (한국시간)에 실행 (UTC 기준으로는 23시)
    - cron: "0 23 * * *"
  workflow_dispatch: # 수동 실행도 가능하게 함

jobs:
  send-snippets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests notion-client

      - name: Run Snippet Sender
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: |
          python aaa.py --token $NOTION_TOKEN

