# 이 파일은 .github/workflows/automation.yml 경로에 저장됩니다.
name: Daily Snippet Automation

# -------------------------------------------------------------
# 1. 언제 실행할지 정하는 규칙입니다. (트리거)
# -------------------------------------------------------------
on:
  schedule:
    # cron 문법: '분 시 일 월 요일' 순서입니다.
    # 매일 23시 00분 (UTC 기준)에 실행하라는 뜻입니다.
    # UTC 23시는 한국 시간(KST)으로 다음 날 아침 8시입니다.
    - cron: '0 23 * * *'
  
  # 이 부분은 Actions 탭에서 수동으로 실행할 수 있는 버튼을 만들어줍니다.
  # 테스트할 때 아주 유용합니다.
  workflow_dispatch:

# -------------------------------------------------------------
# 2. 어떤 작업을 할지 정하는 곳입니다. (재료 및 요리 순서)
# -------------------------------------------------------------
jobs:
  # 'run-script'라는 이름의 작업을 만듭니다.
  run-script:
    # 이 작업은 최신 우분투(리눅스) 컴퓨터에서 실행됩니다.
    runs-on: ubuntu-latest

    # 작업의 순서(단계)를 정합니다.
    steps:
      # 1단계: 저장소에 있는 코드를 다운로드합니다.
      - name: Check out repository
        uses: actions/checkout@v3

      # 2단계: 파이썬 3.11 버전을 설치합니다.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3단계: 스크립트에 필요한 부품(라이브러리)들을 설치합니다.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install notion-client requests pytz

      # 4단계: 드디어 우리의 파이썬 스크립트를 실행합니다.
      - name: Run daily snippet script
        env:
          # 아까 우리가 저장한 비밀(NOTION_TOKEN)을 스크립트가 사용할 수 있도록 '환경 변수'로 넣어줍니다.
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        # 'aaa.py'를 실행하라는 명령어입니다.
        run: python aaa.py
